name: bip39_hcb
description: Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
version: 1.0.4
homepage: https://github.com/anicdh/bip39
author: anicdh <email@example.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  pointycastle_hcb:
    git: 
      url: https://github.com/kithau-hcb/pc-hcb.git
      ref: 'hcb-1.0.2'
  hex: ^0.1.2
  crypto: ^2.0.3
dev_dependencies:
  test: ^1.0.0
